version: 0.0
os: linux
files:
  - source: target/java-spring-boot-application-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
